version: "3.9"
services:
  deepdrr:
    # image: ghcr.io/pelvisvr/deepdrr_zmq:master
    # environment:
    #   - PATIENT_DATA_DIR=/patientdata
    #   - LOG_DIR=/logdata
    #   - DEEPDRR_DATA_DIR=/deepdrrcache
    pull_policy: build
    build:
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute, graphics]
              # capabilities: [gpu, utility, compute, graphics, video, display]
              # device_ids: