name: deepdrr
channels:
  - pytorch
  - "nvidia/label/cuda-11.8.0"
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-nvprof
  - cuda-profiler-api
  - pip
  - pip:
      - -r requirements.txt
      - -e .
