name: deepdrr-dev
channels:
  - pytorch
  - "nvidia/label/cuda-11.8.0"
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  # - pycuda
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - pip
  - pip:
      - -r requirements.txt
      - -e .
      - trame
      - ipykernel
      - ipywidgets
#mamba env create -f environment-dev.yml
