name: deepdrr2
channels:
  - pytorch
  - "nvidia/label/cuda-12.1.1"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-profiler-api
  - cupy
  - pip
  # - pip:
  #     - -r requirements.txt
  #     # - -e . # disabled for docker
