name: deepdrr
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - cudatoolkit=11.1
  - cudatoolkit-dev=11.1
  - pycuda # https://github.com/harskish/ganspace/issues/9#issuecomment-730056660
  - pip
  - pip:
      - -r requirements.txt
      - -e .
